#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const envPath = path.join(__dirname, '..', '.env');
const envExamplePath = path.join(__dirname, '..', '.env.example');

console.log('🔧 QBench Test Automation - Environment Setup\n');

// Check if .env already exists
if (fs.existsSync(envPath)) {
  rl.question('⚠️  .env file already exists. Do you want to overwrite it? (y/N): ', (answer) => {
    if (answer.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      process.exit(0);
    }
    setupEnvironment();
  });
} else {
  setupEnvironment();
}

function setupEnvironment() {
  const questions = [
    {
      key: 'BASE_URL',
      question: 'Enter the base URL for your application',
      default: 'https://srqaengineer-ns-uat.qbench.net/',
      validate: (value) => value.startsWith('http')
    },
    {
      key: 'TEST_EMAIL',
      question: 'Enter the test user email',
      default: null,
      validate: (value) => value.includes('@'),
      required: true
    },
    {
      key: 'TEST_PASSWORD',
      question: 'Enter the test user password',
      default: null,
      validate: (value) => value.length > 0,
      required: true,
      hidden: true
    },
    {
      key: 'HEADLESS',
      question: 'Run tests in headless mode? (true/false)',
      default: 'true',
      validate: (value) => ['true', 'false'].includes(value.toLowerCase())
    },
    {
      key: 'DEFAULT_TIMEOUT',
      question: 'Default timeout in milliseconds',
      default: '30000',
      validate: (value) => !isNaN(parseInt(value))
    }
  ];

  const envContent = [];
  let currentIndex = 0;

  function askQuestion() {
    if (currentIndex >= questions.length) {
      writeEnvFile();
      return;
    }

    const q = questions[currentIndex];
    const promptText = q.default 
      ? `${q.question} [${q.default}]: `
      : `${q.question}: `;

    rl.question(promptText, (answer) => {
      const value = answer.trim() || q.default;

      if (!value && q.required) {
        console.log(`❌ ${q.key} is required.`);
        askQuestion(); // Ask again
        return;
      }

      if (value && q.validate && !q.validate(value)) {
        console.log(`❌ Invalid value for ${q.key}.`);
        askQuestion(); // Ask again
        return;
      }

      if (value) {
        envContent.push(`${q.key}=${value}`);
        if (!q.hidden) {
          console.log(`✅ ${q.key} set to: ${value}`);
        } else {
          console.log(`✅ ${q.key} set (hidden)`);
        }
      }

      currentIndex++;
      askQuestion();
    });
  }

  function writeEnvFile() {
    // Add header
    const header = [
      '# QBench Test Automation Environment Configuration',
      '# Generated by setup-env.js',
      '# ' + new Date().toISOString(),
      '',
      '# IMPORTANT: Never commit this file to version control!',
      '# Add .env to your .gitignore file',
      '',
      ...envContent
    ].join('\n');

    fs.writeFileSync(envPath, header);
    
    console.log('\n✅ Environment configuration saved to .env');
    console.log('📝 You can modify these values by editing the .env file directly.');
    console.log('🔒 Remember: Never commit the .env file to version control!');
    console.log('\nYou can now run tests with: npm test');
    
    rl.close();
  }

  askQuestion();
}

rl.on('close', () => {
  process.exit(0);
});